### PR TITLE
Add Tiniest Obj Loader.

### PR DESCRIPTION
**Pull request by Rinnegatamante**

### CODE REVIEW

**Comment by isage** [comment]
There's zero point in having it in packages.
Just make in header-only and include with your vitagl samples.

**Comment by joel16** [comment]
I agree with isage, since this is only within vitaGL's samples it doesn't necessarily have to be a library inside of vitasdk.

**Comment by Rinnegatamante** [comment]
> I agree with isage, since this is only used within vitaGL's samples it doesn't necessarily have to be a library inside of vitasdk.

You do realize the scope of vdpm is to provide libs for creation of new brand new homebrews as well and not just port/adapt pre-existing code?

Can the lib be useful for people working on brand new content? Yes.
Does vdpm provide any asset loading library? No (or else i wouldn't have even wasted my time writing this).

With that being said, i don't care if you want to merge it or not, not gonna spend any more time discussing with vitriol poisoned haters.

**Comment by isage** [comment]
@d3m3vilurr that "lib" is literally two (poorly written - no error checking for malloc fails, etc.) functions that could be made inline.
He won't listen anyway (at least in public, he can only do that silently behind backs, like the thief he is, so he can then say it was his great idea), so why bother.

**Comment by d3m3vilurr** [comment]
ok. i'll modify some personal assault part.

**Comment by isage** [comment]
Right, i forgot that it's only ok when you do that.

**Comment by Rinnegatamante** [comment]
> Right, i forgot that it's only ok when you do that.

Right, i forgot the part where you and your clown friends shittalk about everything i do on Discord whilst i don't give a shit about your silly lives.

**Comment by isage** [comment]
You should stop lurking there via alt and taking notes if you oh sooo don't care

**Comment by d3m3vilurr** [comment]
please stop insulting.

@Rinnegatamante because his first part is picking the fixing point. he is right you forget the memory check.
and second part is an answer of my question.

**Pull request merged**
