### PR TITLE
Remove kuio

### PR DESCRIPTION
**Pull request by Princess-of-Sleeping**
And also it vulnerable
- Allow to Overwrite `path` while processing waiting current io request by another process
- Allow to Overwrite `io type` while processing waiting current io request by another process
- Allow to Overwrite `kernel rw buffer` while processing waiting current io request by another process
- Allow to close kernel fd by kuIoClose
- Allow to open ux0:data path in kuio SAFE_MODE

maybe more...

### CODE REVIEW

**Comment by Princess-of-Sleeping** [comment]
The following changes broke taipool compatibility
https://github.com/vitasdk/vita-headers/pull/539

**Comment by Princess-of-Sleeping** [comment]
Compatibility fixed

**Comment by d3m3vilurr** [comment]
maybe we just need to remove it from [vpdm](https://github.com/vitasdk/vdpm/blob/969a689/include/install-packages.sh#L61) and to add warning message into VITABUILD script than purge it from packages repo.

**Comment by Rinnegatamante** [comment]
What are the currently suggested way to open filehandles in a user plugin? If i remember correctly, sceIo just has issues opening files in user plugins.

**Comment by SonicMastr** [comment]
ioPlus already mostly handles that functionality globally with a single patch. Only downside being it bypasses restrictions in safe mode, so people will have to sacrifice that. It takes a safer and more simplistic approach. Specific `ftell` functionality isn't built in, but can easily be recreated through getting the return of sceIoLSeek with an offset of 0. It also removes the need to change any existing SceIofilemgr code and to link any extra libs.

**Comment by SonicMastr** [comment]
While outright removal right now would be abrupt, it would be better to provide a warning that it's deprecated and make the choice to remove it later. Most of the vulnerabilities seem to be from kuio's threaded nature and going with ioPlus would be both safer and easier in the long run with little to no chance of race conditions and no changes to the way devs have to interact with IO functionality themselves.

**Comment by Princess-of-Sleeping** [comment]
Many problems can be solved by changing the position of the mutex/sema.
But since kuio uses guids, this is very dangerous as the user can manipulate the io guid.

**Comment by Rinnegatamante** [comment]
If there are valid alternatives, i'm ok with removing it too. No need to deprecate it first since it always seen little usage so the few projects still using it are not a big loss and can be adapted easily.

@d3m3vilurr are you ok with this?

**Pull request closed without merging**
