### PR TITLE
Added Box2D.

### PR DESCRIPTION
**Pull request by Rinnegatamante**

### CODE REVIEW

**Comment by devnoname120** [comment]
Please rebase.

**Comment by Rinnegatamante** [comment]
Build failing cause opus. I suggest an URL change for that library.

**Comment by devnoname120** [comment]
I suggest you to use the tarballs from github: https://github.com/xiph/opus/releases

**Comment by devnoname120** [comment]
Could you rebase on master? https://github.com/vitasdk/packages/commit/fcd0c856088be99c5cf3f0978797d79c92662fe8

**Pull request closed without merging**
