### PR TITLE
Update GitHub workflows

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by sharkwouter** [comment]
Is ubuntu-latest now 20.04 or 22.04?

**Comment by isage** [comment]
22.04

**Comment by scribam** [comment]
According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources, ubuntu-latest = ubuntu-20.04

**Review by sharkwouter — APPROVED** [review]
It's a little bit risky to set it to latest, since what latest is will change, but it might be worthwhile doing to make sure we stay up-to-date.

**Comment by scribam** [comment]
https://github.com/vitasdk/packages/actions/runs/3229262747

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/upload-artifact, actions/checkout

An other deprecation message from GitHub Actions which will be fixed with this PR

**Pull request closed without merging**
