### PR TITLE
- Add bullet physics library.

### PR DESCRIPTION
**Pull request by DrakonPL**

### CODE REVIEW

**Comment by DrakonPL** [comment]
Error is on "cd bullet-physics-vita" line from VITABUILD. Could anyone point me if should i enter to repo folder  name or package name?

**Comment by ebraminio** [comment]
Hi there, I guess you should instead use [a release tarball](https://github.com/DrakonPL/bullet-physics-vita/archive/1.1.tar.gz) from [here](https://github.com/DrakonPL/bullet-physics-vita/releases) then you can easily use its SHA.

**Comment by DrakonPL** [comment]
Thanks for comment. Also sorry for not seeing obvious things... All fixed and commited.

**Comment by devnoname120** [comment]
No worries. :)

**Comment by devnoname120** [comment]
Could you update this list accordingly?
https://github.com/vitasdk/vdpm/blob/master/include/install-packages.sh

**Pull request merged**
