### PR TITLE
Curl: switch to upstream and update to 8.3.0

### PR DESCRIPTION
**Pull request by isage**

### CODE REVIEW

**Comment by isage** [comment]
Drafted for now, as i'd like to use mbedtls for backend

**Comment by isage** [comment]
Should be merged after https://github.com/vitasdk/packages/pull/242

**Comment by isage** [comment]
See cmake params. fcntl disabled. SO_NONBLOCK is autodetected

**Comment by scribam** [comment]
Can you rebase your PR? This will trigger the CI to make sure it builds fine

**Comment by isage** [comment]
It's been so long i already forgot why i even wanted that.

**Review by scribam — APPROVED** [review]

**Comment by isage** [comment]
It's been 11 months, 12 curl versions and two rebases...

**Review by scribam — APPROVED** [review]

**Comment by d3m3vilurr** [comment]
@isage can you revert to openssl? or how about make the new package for example `curl-mbedtls`

**Comment by isage** [comment]
It took you almost a year for that?
No. The whole point was to not depend on bloated openssl

**Pull request closed without merging**
