### PR TITLE
Drop unmaintained vita-libdl

### PR DESCRIPTION
**Pull request by isage**
* vita-libdl repo is archived and unmaintained
* it never really worked (https://github.com/hyln9/vita-libdl/issues/1)
* the only thing using it and why it was added to packages (vita-luajit) is archived too
* Fails to build with latest sdk, which breaks CI for other packages

### CODE REVIEW

**Review by sharkwouter — APPROVED** [review]
Makes sense. Will you upload your implementation later?

**Comment by isage** [comment]
I can if there's demand for it.

**Comment by sharkwouter** [comment]
This might cause an issue with the automatic builds for lpp-vita because of this: https://github.com/Rinnegatamante/lpp-vita/pull/56

**Comment by isage** [comment]
So does it work for lpp or not? https://github.com/Rinnegatamante/lpp-vita/pull/41
i see few solutions:
1. drop it
2. someone should pick it up and maintain, so we switch to it
3. switch to my impl as long as it works for lpp

**Comment by v-atamanenko** [comment]
As a quickest and easiest solution, I suggest to use this: https://github.com/v-atamanenko/vita-libdl
It only has the compilation issue fixed, other problems not addressed. In other words, should be enough to preserve the status-quo at least

**Comment by isage** [comment]
Question is: if it's broken (crashes lpp), why do we need it?

**Comment by isage** [comment]
pullrequest it then

**Comment by d3m3vilurr** [comment]
replaced #226

**Pull request closed without merging**
