### PR TITLE
Add unrar

### PR DESCRIPTION
**Pull request by d3m3vilurr**

### CODE REVIEW

**Comment by devnoname120** [comment]
Please don't use a repository with an extracted tarball:

Either:
- Fork a Github mirror, do a commit to add the Vita Makefile, and use it. (Better)
- Use the tarball directly and add a `.patch` file.

**Comment by d3m3vilurr** [comment]
1. it's not my repo and rarlab only provide tarball. so cannot fork only can extract tarball.
2. tarball and patch probably make sense if `packages` contain all third party projects for vita. like another package managers.
    so, currently i'm partially argree your opinion, and maybe we need to receive patch from @soarqin
3. well, or  we can make new project for this then manager more generically. (still need confirming from @soarqin)
4. and my question, is this new rule? current `packages` contains both cases.

**Comment by devnoname120** [comment]
1. Right, I meant it in the general case.
2. I'm not sure to understand what you mean. We can get a patch file easily by doing a `git diff` between the [base source](http://www.rarlab.com/rar/unrarsrc-5.4.5.tar.gz), and the [Vita port](https://github.com/soarqin/vita-unrar).
3. What do you mean with "we can make new project for this then manager more generically"?
4. Well not really, but I thought that it made more sense.

**Comment by soarqin** [comment]
@d3m3vilurr I stopped maintaining my unrar port, because I prefer porting libarchive.
The only problem is that rar5 format is not currently supported (the issue might be libarchive/libarchive#373)
Anyhow I will make a patch and add it to my repo later.

**Comment by d3m3vilurr** [comment]
@devnoname120  well, i was wrong wrote something, i mean `if we want to manage all projects in ``vitasdk packages`` project`

at least this case, you are right. but this rule is sometimes sense but also can be non-sense
for example in #5, why you fork from mirror? you can add just patch files. :-/ 
and many package managing systems work like that;

1. still need managing source code like your fork repo.
2. so they assigned `commiter` for following newer source code like this.
3. then package tree just contains diff patchsets.

so i mean, rule is generic, right, but little annoying. because we did't choose someone for the this role. :)

**Comment by soarqin** [comment]
@d3m3vilurr I've force pushed a new commit with patch here: https://github.com/soarqin/vita-unrar/blob/master/patches/vita.patch
I've also removed my changes used to fix compiling warnings, in order to make this minimal patch which could be easier to fit future unrar releases.

**Comment by d3m3vilurr** [comment]
@soarqin I like that, i'll change this pr :D

**Pull request merged**
