### PR TITLE
box2d: add proper box2d package

### PR DESCRIPTION
**Pull request by Cpasjuste**
Please not that this is build from latest box2d sources (stable release), headers location changed from version 3.x.x which could brake some homebrews (need to correct includes paths in homebrews).

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
IMO, it should split/change the package to `box2d` & `box2d-git`.
also need to add `conflicts` informations

**Comment by Cpasjuste** [comment]
Hi there,

Yep, forgot about conflicts, will take a look tomorrow. Else i don't think we should keep the other one, it's very old and incomplete (missing important classes).

**Comment by d3m3vilurr** [comment]
oh, i thought that is future version, it just old version & @Rinnegatamante's fork.
so in that case package name could change `box2d-14` or `box2d-14mod`

**Comment by Cpasjuste** [comment]
Hi @d3m3vilurr , i think we should not keep the @Rinnegatamante "hack", i don't see the point. Maybe @Rinnegatamante can confirm this, there is maybe a good reason (newer box2d is compatible with older ones, just header location changed).

**Comment by Rinnegatamante** [comment]
The Box2D old package was literally stripped from Numpty Physics  repo to make it compileable easily with vitasdk. If the new Box2D works fine, i see no reason to keep the older package indeed.

**Pull request merged**
