### PR TITLE
Added jsoncpp

### PR DESCRIPTION
**Pull request by sharkwouter**
This is a nice library to use for reading json. There is an example for it which works on the Vita here: https://github.com/sharkwouter/jsoncpp-vita

### CODE REVIEW

**Comment by Rinnegatamante** [comment]
Add the library here in order to let travis compile it: https://github.com/vitasdk/packages/blob/master/travis_packages.sh

**Comment by sharkwouter** [comment]
I've added it to the travis_packages.sh script, hope it builds.

**Comment by sharkwouter** [comment]
Seems vitaGL failed to build for some reason. I don't think that's related to this PR, though.

**Comment by Rinnegatamante** [comment]
Yep, i've opened a PR that solves that issue. Once it's merged, we'll re-launch build and see if everything's fine.

**Pull request merged**
