### PR TITLE
openal-soft: fix source url

### PR DESCRIPTION
**Pull request by scribam**
https://openal-soft.org/ is down

### CODE REVIEW

**Comment by isage** [comment]
I don't think github guarantees constant sha sum for archives

**Comment by scribam** [comment]
Some packages use archive and have sha sum:
https://github.com/vitasdk/packages/blob/67e584be6a2bafb2f5e6bf6369e647dd1eb08dd8/assimp/VITABUILD#L5-L6
https://github.com/vitasdk/packages/blob/67e584be6a2bafb2f5e6bf6369e647dd1eb08dd8/cpr/VITABUILD#L5-L6

But I can skip the sha sum check if you prefer

**Comment by isage** [comment]
Yeah, because i keep forgetting about that too. Honestly, i don't think they change. Just not guaranteed not to.
@d3m3vilurr your call

**Comment by scribam** [comment]
Found a post from GitHub about it: https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

> GitHub doesn’t guarantee the stability of checksums for automatically generated archives. These are marked with the words “Source code (zip)” and “Source code (tar.gz)” on the Releases tab. If you need to rely on a consistent checksum, you may upload archives directly to GitHub Releases.
These are guaranteed not to change.

**Review by sharkwouter — APPROVED** [review]

**Pull request merged**
