### PR TITLE
Update GLM to 0.9.9.4

### PR DESCRIPTION
**Pull request by v-atamanenko**
So far seems to work normally for me, will undraft after some more tests.
UPD: Works great 👍🏽

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
I checked both of arch's patch & glm repo.
arch team removed the GCC hack at [0.9.9.6](https://github.com/archlinux/svntogit-community/commit/838ef898c3fef)
but imo, glm team patched it at [0.9.9.4](https://github.com/g-truc/glm/releases/tag/0.9.9.4)
so this patch looks good to me.

btw I have one question, can you explain why don't you update to 0.9.9.8?

**Comment by v-atamanenko** [comment]
@d3m3vilurr I don't know how but I missed that there is newer version. Also with some Neon optimizations, seemingly. Alright, I'll draft this again and test the newest one

**Comment by scribam** [comment]
@d3m3vilurr @v-atamanenko I have updated glm with version 1.0.1. This PR can be closed

**Comment by v-atamanenko** [comment]
cool, thanks!

**Pull request closed without merging**
