### PR TITLE
Add libsmb2.

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Review by sharkwouter — CHANGES_REQUESTED** [review]
Can you set a specific commit or version and set the license field?

**Comment by Wolf3s** [comment]
I did it, also i linked to the license

> Can you set a specific commit or version and set the license field?

**Comment by d3m3vilurr** [comment]
you need to recheck destdir path.

please see another package files which use `cmake` :)

**Comment by Wolf3s** [comment]
> you need to recheck destdir path.
> 
> please see another package files which use `cmake` :)

Most of them uses the make as command but i will see unfortunally i can't test it on my machine because it's on root :)

**Comment by d3m3vilurr** [comment]
sorry I'm late. and thank you for your contribution and patient

**Comment by Wolf3s** [comment]
> sorry I'm late. and thank you for your contribution and patient

Thanks, I hope that i can contribute more to psvita community.

**Pull request merged**
