### PR TITLE
Add xz

### PR DESCRIPTION
**Pull request by cmsj**

### CODE REVIEW

**Comment by cmsj** [comment]
(Note this isn't tested locally yet)

**Comment by TheOfficialFloW** [comment]
Shouldn't `xz` be add before `libarchive`?

**Comment by TheOfficialFloW** [comment]
Also remove
```
prepare() {
  cd ${pkgname}-${pkgver}
}
```
and add

`cd ${pkgname}-${pkgver}` to `build`

to fix build failure.

**Comment by cmsj** [comment]
Done, thanks. I really should have tested it locally before pushing the PR :)

**Pull request merged**
