### PR TITLE
Update harfbuzz to 1.4.8

### PR DESCRIPTION
**Pull request by ebraminio**
Hopefully no local patches anymore.

### CODE REVIEW

**Comment by devnoname120** [comment]
Have you tested it to make sure that the new version works properly on the vita?

**Comment by ebraminio** [comment]
I never ran a complete example for this but a compile error was blocking this to work and I fixed the upstream (which I am maintainer) to work without any needed patch so now that CI agrees this, this is safe to merge AFAICS.

**Comment by ebraminio** [comment]
I mean, the same patch here is now upstream, so the port is somehow identical regardless.

**Comment by devnoname120** [comment]
Alright, let's merge it.

**Pull request merged**
